name: macro_curves

dependencies:
  - python=3.11
  - pip=23.0
  - pip:
    - urllib3==1.26.17
    - numpy==1.24.3
    - scipy==1.10.1
    - pydantic==2.1.1
    - sortedcontainers==2.4.0
    - holidays==0.34
    - pandas==2.0.1
    - plotly==5.16.1